// template data
export const books = [
  {
    id: 0,
    title: "Concrete Mathematics",
    author: "Donald Knuth, Oren Patashnik y Ronald Graham",
    category: "Maths",
    pages: "800",
    year: "1988",
    image: "https://m.media-amazon.com/images/I/61u4nLxDGPL._AC_SY780_.jpg",
  },
  {
    id: 1,
    title: "Clean Code",
    author: "Robert C. Martin ",
    category: "Computer",
    pages: "800",
    year: "2008",
    image: "https://m.media-amazon.com/images/I/41xShlnTZTL._AC_SY780_.jpg",
  },
  {
    id: 2,
    title: "Cosmos",
    author: "Carl Sagan",
    category: "Science",
    pages: "800",
    year: "1988",
    image:
      "https://images.cdn3.buscalibre.com/fit-in/360x360/e0/f2/e0f299b5184dddfb41d39724f75349b8.jpg",
  },
  {
    id: 3,
    title: "Thomas' Calculus",
    author: "George B. Thomas",
    category: "Maths",
    pages: "800",
    year: "1963",
    image: "https://m.media-amazon.com/images/I/41IOFosuLPL.jpg",
  },
  {
    id: 4,
    title: "The C Programming Language",
    author: "Brian Kernighan y Dennis Ritchie ",
    category: "Computer",
    pages: "800",
    year: "1978",
    image:
      "https://images.cdn3.buscalibre.com/fit-in/360x360/41/66/416631b1eaef27333a77c60d780e065d.jpg",
  },
  {
    id: 5,
    title: "A Brief History Of Time",
    author: "Stephen Hawking",
    category: "Science",
    pages: "800",
    year: "1988",
    image: "https://m.media-amazon.com/images/I/51+GySc8ExL._AC_SY780_.jpg",
  },
  {
    id: 6,
    title: "Discrete and Combinatorial Mathematics",
    author: "Ralph Grimaldi",
    category: "Maths",
    pages: "800",
    year: "1985",
    image: "https://m.media-amazon.com/images/I/81VyD4JjhML.jpg",
  },
];
